### ISSUE TITLE
BUG : Context Overridden in Batched Events by Batch Context in v1.1.3

### ISSUE THREAD

**Issue by dankaiser1808** [rudderlabs/rudder-sdk-rust#22]
### Version Affected
Latest Version: 1.1.3

### Description
In the Rudder SDK Rust implementation, there's an issue where the context of individual events (Track, Identify, Page, etc.) is being overridden by the batch context during the merge process. The core of the problem lies in the function responsible for merging contexts, located at [utils.rs#L23](https://github.com/rudderlabs/rudder-sdk-rust/blob/master/src/utils.rs#L23), which does not differentiate between the default context, the batch-level context, and the individual event's context. Consequently, even in the absence of a batch-level context, the default context values can override those set at the individual event level, leading to a loss of context specificity for events.

This issue is particularly evident in the handling of the context for Track events, as observed in [utils.rs#L279](https://github.com/rudderlabs/rudder-sdk-rust/blob/master/src/utils.rs#L279), where the context of the Track event is overridden by the modified context during the batching process.

### Steps to Reproduce
Create a batched event (Track, Identify, Page, etc.) with a context set.
Use the client send method to send the batched event.
Observe that the context of the event is overridden by the batch or default context.

### Expected Behavior
The expected behavior should ensure that the context of individual events, regardless of their type, is preserved and accurately represented in the final event data when they are batched. Two potential approaches to address this issue are:

**Context Merge Handling**: Implement a merge process that includes the context of all event types that can be batched. This process should also handle conflicts gracefully, such as when the same key is present in both the batch context and the individual event context.

**Selective Merge Strategy**: If an event context is explicitly set, it should only merge with the default context, ensuring that the event-specific context is prioritized and preserved across all event types that can be batched.

**Comment by MoumitaM** [comment]
Hi @dankaiser1808,
Thank you for raising this. We will take a look.

**Comment by MoumitaM** [comment]
Hi @dankaiser1808,
We released a new version(1.1.4) with the fix.
